### ISSUE TITLE
Memory leak due to bound callback

### ISSUE THREAD

**Issue by tohein** [glimix/limix-inference#14]
Hi,
LMM passes a bound method as a callback to an optimix Scalar / ndarray-listener. I believe this leads to a memory leak as instantiations of LMM will not be removed by the GC unless  _logistic is de-referenced as well.

https://github.com/limix/glimix-core/blob/8cd41cebf6e1e46f298dfd2533a87741bd7a3a6d/glimix_core/lmm/_lmm.py#L110

A solution could be a wrapper class implementing weak references as described here:
https://www.oreilly.com/library/view/python-cookbook/0596001673/ch05s15.html

Best,
Tobias

**Comment by horta** [comment]
Thanks a lot, @tohein !

I've started working on that: https://github.com/limix/ndarray-listener/commit/9c52cbc1c9ac3439a220c8f3205772b7becdf420

I will make some changes on optimix and then glimix-core, and release everything (hopefully) by tomorrow =)
