### ISSUE TITLE
Memory leak due to the use of functools lru_cache with class methods

### ISSUE THREAD

**Issue by tohein** [glimix/limix-inference#15]
Hi,
class method _logdetXX of LMM is cached using functools lru_cache. Calling .fit() or .lml(), which both rely on _logdetXX will prevent the LMM instance to be accessible to garbage collection until the cache is cleared (and listeners are removed, see issue #14).

https://github.com/limix/glimix-core/blob/8cd41cebf6e1e46f298dfd2533a87741bd7a3a6d/glimix_core/lmm/_lmm.py#L457

See also
https://stackoverflow.com/questions/33672412/python-functools-lru-cache-with-class-methods-release-object

Best,
Tobias

**Comment by horta** [comment]
I believe the version 3.1.12 fixes that issues. Thank you again for reporting it!
